name: Bors Pull Request CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  ci-check-bors:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        timeout-minutes: 1
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: test
        timeout-minutes: 10
        run: |
          pip install pyyaml
          pip install toml
          python ./cicd_utils/validate_bors_config.py
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11.0.11+9

      - name: Build and test
        run: ./gradlew build -x :smoke-tests:test --no-daemon
  publish:
    needs: [ ci-check-bors, build-and-test ]
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11.0.11+9
      - name: publish
        run: export OSSRH_JIRA_USERNAME=${{secrets.OSSRH_JIRA_USERNAME}}; export OSSRH_JIRA_PASSWORD=${{secrets.OSSRH_JIRA_PASSWORD}}; ./gradlew publish